// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsFab5CTAtnu_o4V2TLVBzdkNN3mm0aAY',
    appId: '1:887434577231:web:098f93643f142f9381713a',
    messagingSenderId: '887434577231',
    projectId: 'cantina-manager-557e5',
    authDomain: 'cantina-manager-557e5.firebaseapp.com',
    storageBucket: 'cantina-manager-557e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7GP5Z7-ZuLVslRFeAz7IpOD5vjqmFwvI',
    appId: '1:887434577231:android:b36fab9661780a2b81713a',
    messagingSenderId: '887434577231',
    projectId: 'cantina-manager-557e5',
    storageBucket: 'cantina-manager-557e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBelJo4h-SZhTetlsK-DrItbcJlgbp1myM',
    appId: '1:887434577231:ios:a3c98f915b9eda5c81713a',
    messagingSenderId: '887434577231',
    projectId: 'cantina-manager-557e5',
    storageBucket: 'cantina-manager-557e5.firebasestorage.app',
    iosBundleId: 'com.example.cantinaManager3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBelJo4h-SZhTetlsK-DrItbcJlgbp1myM',
    appId: '1:887434577231:ios:a3c98f915b9eda5c81713a',
    messagingSenderId: '887434577231',
    projectId: 'cantina-manager-557e5',
    storageBucket: 'cantina-manager-557e5.firebasestorage.app',
    iosBundleId: 'com.example.cantinaManager3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsFab5CTAtnu_o4V2TLVBzdkNN3mm0aAY',
    appId: '1:887434577231:web:c535195c4f6ef11e81713a',
    messagingSenderId: '887434577231',
    projectId: 'cantina-manager-557e5',
    authDomain: 'cantina-manager-557e5.firebaseapp.com',
    storageBucket: 'cantina-manager-557e5.firebasestorage.app',
  );
}
